server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          # uri: https://git.oschina.net/it-much/config-repo-51cto-video
          uri: https://github.com/sqskg/spring-config-repo
          username: sqskg@163.com
          password: Sqs512sqs
          
